---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogsite-blog-service-deployment-loadbalancer
  labels:
    app: blogsite-blog-service-app-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogsite-blog-service-app-loadbalancer
  template:
    metadata:
      labels:
        app: blogsite-blog-service-app-loadbalancer
    spec:
      containers:
        - name: blogsite-blog-service-app-loadbalancer
          image: piyushdubey1994/blogsite-blog-service:tagversion
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: blogsite-blog-service-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: blogsite-blog-service-app-loadbalancer
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8083